// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PackageDeliverySystem.DataAccess.DataAccess;

#nullable disable

namespace PackageDeliverySystem.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260305161420_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PackageDeliverySystem.Models.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 Hill St, Derry",
                            Email = "emma.oconnor@email.com",
                            Name = "Emma OConnor",
                            PhoneNumber = "0871234501"
                        },
                        new
                        {
                            Id = 2,
                            Address = "4 Main Rd, Letterkenny",
                            Email = "sophie.gallagher@email.com",
                            Name = "Sophie Gallagher",
                            PhoneNumber = "0871234502"
                        },
                        new
                        {
                            Id = 3,
                            Address = "8 River Walk, Buncrana",
                            Email = "aoife.kelly@email.com",
                            Name = "Aoife Kelly",
                            PhoneNumber = "0871234503"
                        },
                        new
                        {
                            Id = 4,
                            Address = "22 Oak Ave, Dublin",
                            Email = "sarah.murphy@email.com",
                            Name = "Sarah Murphy",
                            PhoneNumber = "0871234504"
                        },
                        new
                        {
                            Id = 5,
                            Address = "9 Park Lane, Cork",
                            Email = "lucy.boyle@email.com",
                            Name = "Lucy Boyle",
                            PhoneNumber = "0871234505"
                        },
                        new
                        {
                            Id = 6,
                            Address = "1 Green Rd, Galway",
                            Email = "grace.dunne@email.com",
                            Name = "Grace Dunne",
                            PhoneNumber = "0871234506"
                        },
                        new
                        {
                            Id = 7,
                            Address = "3 Harbour View, Sligo",
                            Email = "mia.quinn@email.com",
                            Name = "Mia Quinn",
                            PhoneNumber = "0871234507"
                        },
                        new
                        {
                            Id = 8,
                            Address = "7 Meadow Rd, Limerick",
                            Email = "hannah.ward@email.com",
                            Name = "Hannah Ward",
                            PhoneNumber = "0871234508"
                        },
                        new
                        {
                            Id = 9,
                            Address = "14 Bridge St, Waterford",
                            Email = "chloe.reid@email.com",
                            Name = "Chloe Reid",
                            PhoneNumber = "0871234509"
                        },
                        new
                        {
                            Id = 10,
                            Address = "6 Hilltop, Donegal",
                            Email = "ella.ferry@email.com",
                            Name = "Ella Ferry",
                            PhoneNumber = "0871234510"
                        },
                        new
                        {
                            Id = 11,
                            Address = "18 Pine Rd, Armagh",
                            Email = "lily.kane@email.com",
                            Name = "Lily Kane",
                            PhoneNumber = "0871234511"
                        },
                        new
                        {
                            Id = 12,
                            Address = "5 Cedar Ave, Newry",
                            Email = "zoe.moore@email.com",
                            Name = "Zoe Moore",
                            PhoneNumber = "0871234512"
                        },
                        new
                        {
                            Id = 13,
                            Address = "11 Glen St, Dundalk",
                            Email = "isla.byrne@email.com",
                            Name = "Isla Byrne",
                            PhoneNumber = "0871234513"
                        },
                        new
                        {
                            Id = 14,
                            Address = "20 Church Rd, Kilkenny",
                            Email = "freya.sweeney@email.com",
                            Name = "Freya Sweeney",
                            PhoneNumber = "0871234514"
                        },
                        new
                        {
                            Id = 15,
                            Address = "2 Oakfield, Clare",
                            Email = "ruby.mcbride@email.com",
                            Name = "Ruby McBride",
                            PhoneNumber = "0871234515"
                        },
                        new
                        {
                            Id = 16,
                            Address = "17 Riverbank, Mayo",
                            Email = "emily.gillen@email.com",
                            Name = "Emily Gillen",
                            PhoneNumber = "0871234516"
                        },
                        new
                        {
                            Id = 17,
                            Address = "9 Parkview, Wexford",
                            Email = "anna.devlin@email.com",
                            Name = "Anna Devlin",
                            PhoneNumber = "0871234517"
                        },
                        new
                        {
                            Id = 18,
                            Address = "13 Main St, Monaghan",
                            Email = "kate.curran@email.com",
                            Name = "Kate Curran",
                            PhoneNumber = "0871234518"
                        },
                        new
                        {
                            Id = 19,
                            Address = "15 Hillcrest, Derry",
                            Email = "olivia.obrien@email.com",
                            Name = "Olivia OBrien",
                            PhoneNumber = "0871234519"
                        },
                        new
                        {
                            Id = 20,
                            Address = "19 Oak Rd, Strabane",
                            Email = "ava.mclaughlin@email.com",
                            Name = "Ava McLaughlin",
                            PhoneNumber = "0871234520"
                        },
                        new
                        {
                            Id = 21,
                            Address = "21 Harbour St, Galway",
                            Email = "molly.gallagher@email.com",
                            Name = "Molly Gallagher",
                            PhoneNumber = "0871234521"
                        },
                        new
                        {
                            Id = 22,
                            Address = "23 Station Rd, Cork",
                            Email = "evie.kelly@email.com",
                            Name = "Evie Kelly",
                            PhoneNumber = "0871234522"
                        },
                        new
                        {
                            Id = 23,
                            Address = "25 Glen Rd, Dublin",
                            Email = "niamh.murphy@email.com",
                            Name = "Niamh Murphy",
                            PhoneNumber = "0871234523"
                        },
                        new
                        {
                            Id = 24,
                            Address = "27 Bridge Ave, Sligo",
                            Email = "clara.boyle@email.com",
                            Name = "Clara Boyle",
                            PhoneNumber = "0871234524"
                        },
                        new
                        {
                            Id = 25,
                            Address = "29 Meadow View, Letterkenny",
                            Email = "erin.doherty@email.com",
                            Name = "Erin Doherty",
                            PhoneNumber = "0871234525"
                        });
                });

            modelBuilder.Entity("PackageDeliverySystem.Models.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dept")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PPS")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PPS")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 Oak Drive, Derry",
                            DateOfBirth = new DateTime(1990, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dept = 0,
                            Name = "Sean Murphy",
                            PPS = "1234567AB",
                            Password = "pass123",
                            Salary = 35000.0,
                            Username = "driver1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Elm Park, Letterkenny",
                            DateOfBirth = new DateTime(1988, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dept = 0,
                            Name = "Conor Kelly",
                            PPS = "2345678BC",
                            Password = "pass123",
                            Salary = 36000.0,
                            Username = "driver2"
                        },
                        new
                        {
                            Id = 3,
                            Address = "22 Hillcrest, Dublin",
                            DateOfBirth = new DateTime(1992, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dept = 1,
                            Name = "Patrick Doherty",
                            PPS = "3456789CD",
                            Password = "admin123",
                            Salary = 50000.0,
                            Username = "admin1"
                        },
                        new
                        {
                            Id = 4,
                            Address = "7 Meadow View, Derry",
                            DateOfBirth = new DateTime(1999, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dept = 1,
                            Name = "Ethan Curran",
                            PPS = "4567890DE",
                            Password = "admin123",
                            Salary = 52000.0,
                            Username = "admin2"
                        });
                });

            modelBuilder.Entity("PackageDeliverySystem.Models.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptedDeliveries")
                        .HasColumnType("int");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttemptedDeliveries = 0,
                            Cost = 12.99,
                            CustomerId = 1,
                            DeliveryDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "12 Hill St, Derry",
                            RecipientName = "Emma OConnor",
                            Status = 2,
                            Type = 1,
                            Weight = 2.5
                        },
                        new
                        {
                            Id = 2,
                            AttemptedDeliveries = 0,
                            Cost = 4.9900000000000002,
                            CustomerId = 1,
                            DeliveryDate = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "12 Hill St, Derry",
                            RecipientName = "Emma OConnor",
                            Status = 1,
                            Type = 0,
                            Weight = 0.10000000000000001
                        },
                        new
                        {
                            Id = 3,
                            AttemptedDeliveries = 0,
                            Cost = 18.989999999999998,
                            CustomerId = 2,
                            DeliveryDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "4 Main Rd, Letterkenny",
                            RecipientName = "Sophie Gallagher",
                            Status = 0,
                            Type = 1,
                            Weight = 3.2000000000000002
                        },
                        new
                        {
                            Id = 4,
                            AttemptedDeliveries = 0,
                            Cost = 4.5,
                            CustomerId = 2,
                            DeliveryDate = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "4 Main Rd, Letterkenny",
                            RecipientName = "Sophie Gallagher",
                            Status = 2,
                            Type = 0,
                            Weight = 0.10000000000000001
                        },
                        new
                        {
                            Id = 5,
                            AttemptedDeliveries = 0,
                            Cost = 14.5,
                            CustomerId = 3,
                            DeliveryDate = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "8 River Walk, Buncrana",
                            RecipientName = "Aoife Kelly",
                            Status = 2,
                            Type = 1,
                            Weight = 1.8
                        },
                        new
                        {
                            Id = 6,
                            AttemptedDeliveries = 0,
                            Cost = 4.2000000000000002,
                            CustomerId = 3,
                            DeliveryDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "8 River Walk, Buncrana",
                            RecipientName = "Aoife Kelly",
                            Status = 2,
                            Type = 0,
                            Weight = 0.10000000000000001
                        },
                        new
                        {
                            Id = 7,
                            AttemptedDeliveries = 0,
                            Cost = 22.5,
                            CustomerId = 4,
                            DeliveryDate = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "22 Oak Ave, Dublin",
                            RecipientName = "Sarah Murphy",
                            Status = 2,
                            Type = 1,
                            Weight = 4.0
                        },
                        new
                        {
                            Id = 8,
                            AttemptedDeliveries = 0,
                            Cost = 11.75,
                            CustomerId = 4,
                            DeliveryDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "22 Oak Ave, Dublin",
                            RecipientName = "Sarah Murphy",
                            Status = 1,
                            Type = 1,
                            Weight = 2.1000000000000001
                        },
                        new
                        {
                            Id = 9,
                            AttemptedDeliveries = 0,
                            Cost = 3.9900000000000002,
                            CustomerId = 5,
                            DeliveryDate = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "9 Park Lane, Cork",
                            RecipientName = "Lucy Boyle",
                            Status = 0,
                            Type = 0,
                            Weight = 0.10000000000000001
                        },
                        new
                        {
                            Id = 10,
                            AttemptedDeliveries = 0,
                            Cost = 20.0,
                            CustomerId = 5,
                            DeliveryDate = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "9 Park Lane, Cork",
                            RecipientName = "Lucy Boyle",
                            Status = 2,
                            Type = 1,
                            Weight = 3.5
                        },
                        new
                        {
                            Id = 11,
                            AttemptedDeliveries = 0,
                            Cost = 10.75,
                            CustomerId = 6,
                            DeliveryDate = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "1 Green Rd, Galway",
                            RecipientName = "Grace Dunne",
                            Status = 2,
                            Type = 1,
                            Weight = 1.8999999999999999
                        },
                        new
                        {
                            Id = 12,
                            AttemptedDeliveries = 0,
                            Cost = 19.989999999999998,
                            CustomerId = 7,
                            DeliveryDate = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "3 Harbour View, Sligo",
                            RecipientName = "Mia Quinn",
                            Status = 0,
                            Type = 1,
                            Weight = 3.2999999999999998
                        },
                        new
                        {
                            Id = 13,
                            AttemptedDeliveries = 0,
                            Cost = 11.5,
                            CustomerId = 8,
                            DeliveryDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "7 Meadow Rd, Limerick",
                            RecipientName = "Hannah Ward",
                            Status = 2,
                            Type = 1,
                            Weight = 2.0
                        },
                        new
                        {
                            Id = 14,
                            AttemptedDeliveries = 0,
                            Cost = 24.989999999999998,
                            CustomerId = 9,
                            DeliveryDate = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "14 Bridge St, Waterford",
                            RecipientName = "Chloe Reid",
                            Status = 2,
                            Type = 1,
                            Weight = 4.5
                        },
                        new
                        {
                            Id = 15,
                            AttemptedDeliveries = 0,
                            Cost = 12.75,
                            CustomerId = 10,
                            DeliveryDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "6 Hilltop, Donegal",
                            RecipientName = "Ella Ferry",
                            Status = 0,
                            Type = 1,
                            Weight = 2.2999999999999998
                        },
                        new
                        {
                            Id = 16,
                            AttemptedDeliveries = 0,
                            Cost = 4.0999999999999996,
                            CustomerId = 10,
                            DeliveryDate = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "6 Hilltop, Donegal",
                            RecipientName = "Ella Ferry",
                            Status = 2,
                            Type = 0,
                            Weight = 0.10000000000000001
                        },
                        new
                        {
                            Id = 17,
                            AttemptedDeliveries = 0,
                            Cost = 13.4,
                            CustomerId = 11,
                            DeliveryDate = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "18 Pine Rd, Armagh",
                            RecipientName = "Lily Kane",
                            Status = 2,
                            Type = 1,
                            Weight = 2.3999999999999999
                        },
                        new
                        {
                            Id = 18,
                            AttemptedDeliveries = 0,
                            Cost = 21.0,
                            CustomerId = 12,
                            DeliveryDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "5 Cedar Ave, Newry",
                            RecipientName = "Zoe Moore",
                            Status = 1,
                            Type = 1,
                            Weight = 3.7999999999999998
                        },
                        new
                        {
                            Id = 19,
                            AttemptedDeliveries = 0,
                            Cost = 15.99,
                            CustomerId = 13,
                            DeliveryDate = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "11 Glen St, Dundalk",
                            RecipientName = "Isla Byrne",
                            Status = 2,
                            Type = 1,
                            Weight = 2.7000000000000002
                        },
                        new
                        {
                            Id = 20,
                            AttemptedDeliveries = 0,
                            Cost = 23.989999999999998,
                            CustomerId = 14,
                            DeliveryDate = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "20 Church Rd, Kilkenny",
                            RecipientName = "Freya Sweeney",
                            Status = 2,
                            Type = 1,
                            Weight = 4.2000000000000002
                        },
                        new
                        {
                            Id = 21,
                            AttemptedDeliveries = 0,
                            Cost = 8.9900000000000002,
                            CustomerId = 15,
                            DeliveryDate = new DateTime(2025, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "2 Oakfield, Clare",
                            RecipientName = "Ruby McBride",
                            Status = 2,
                            Type = 1,
                            Weight = 1.5
                        },
                        new
                        {
                            Id = 22,
                            AttemptedDeliveries = 0,
                            Cost = 20.989999999999998,
                            CustomerId = 16,
                            DeliveryDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "17 Riverbank, Mayo",
                            RecipientName = "Emily Gillen",
                            Status = 0,
                            Type = 1,
                            Weight = 3.7000000000000002
                        },
                        new
                        {
                            Id = 23,
                            AttemptedDeliveries = 0,
                            Cost = 3.5,
                            CustomerId = 17,
                            DeliveryDate = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "9 Parkview, Wexford",
                            RecipientName = "Anna Devlin",
                            Status = 2,
                            Type = 0,
                            Weight = 0.10000000000000001
                        },
                        new
                        {
                            Id = 24,
                            AttemptedDeliveries = 0,
                            Cost = 12.49,
                            CustomerId = 18,
                            DeliveryDate = new DateTime(2025, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "13 Main St, Monaghan",
                            RecipientName = "Kate Curran",
                            Status = 1,
                            Type = 1,
                            Weight = 2.2000000000000002
                        },
                        new
                        {
                            Id = 25,
                            AttemptedDeliveries = 0,
                            Cost = 19.489999999999998,
                            CustomerId = 19,
                            DeliveryDate = new DateTime(2025, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "15 Hillcrest, Derry",
                            RecipientName = "Olivia OBrien",
                            Status = 2,
                            Type = 1,
                            Weight = 3.3999999999999999
                        },
                        new
                        {
                            Id = 26,
                            AttemptedDeliveries = 0,
                            Cost = 13.99,
                            CustomerId = 20,
                            DeliveryDate = new DateTime(2025, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "19 Oak Rd, Strabane",
                            RecipientName = "Ava McLaughlin",
                            Status = 2,
                            Type = 1,
                            Weight = 2.6000000000000001
                        },
                        new
                        {
                            Id = 27,
                            AttemptedDeliveries = 0,
                            Cost = 22.989999999999998,
                            CustomerId = 21,
                            DeliveryDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "21 Harbour St, Galway",
                            RecipientName = "Molly Gallagher",
                            Status = 2,
                            Type = 1,
                            Weight = 4.0999999999999996
                        },
                        new
                        {
                            Id = 28,
                            AttemptedDeliveries = 0,
                            Cost = 14.49,
                            CustomerId = 22,
                            DeliveryDate = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "23 Station Rd, Cork",
                            RecipientName = "Evie Kelly",
                            Status = 2,
                            Type = 1,
                            Weight = 2.7999999999999998
                        },
                        new
                        {
                            Id = 29,
                            AttemptedDeliveries = 0,
                            Cost = 4.25,
                            CustomerId = 23,
                            DeliveryDate = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "25 Glen Rd, Dublin",
                            RecipientName = "Niamh Murphy",
                            Status = 1,
                            Type = 0,
                            Weight = 0.10000000000000001
                        },
                        new
                        {
                            Id = 30,
                            AttemptedDeliveries = 0,
                            Cost = 21.989999999999998,
                            CustomerId = 24,
                            DeliveryDate = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "27 Bridge Ave, Sligo",
                            RecipientName = "Clara Boyle",
                            Status = 2,
                            Type = 1,
                            Weight = 3.8999999999999999
                        },
                        new
                        {
                            Id = 31,
                            AttemptedDeliveries = 0,
                            Cost = 11.99,
                            CustomerId = 25,
                            DeliveryDate = new DateTime(2025, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "29 Meadow View, Letterkenny",
                            RecipientName = "Erin Doherty",
                            Status = 2,
                            Type = 1,
                            Weight = 2.1000000000000001
                        },
                        new
                        {
                            Id = 32,
                            AttemptedDeliveries = 0,
                            Cost = 9.9900000000000002,
                            CustomerId = 2,
                            DeliveryDate = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "4 Main Rd, Letterkenny",
                            RecipientName = "Sophie Gallagher",
                            Status = 2,
                            Type = 1,
                            Weight = 1.7
                        },
                        new
                        {
                            Id = 33,
                            AttemptedDeliveries = 0,
                            Cost = 9.9900000000000002,
                            CustomerId = 5,
                            DeliveryDate = new DateTime(2025, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "9 Park Lane, Cork",
                            RecipientName = "Lucy Boyle",
                            Status = 2,
                            Type = 1,
                            Weight = 1.6000000000000001
                        },
                        new
                        {
                            Id = 34,
                            AttemptedDeliveries = 0,
                            Cost = 19.5,
                            CustomerId = 10,
                            DeliveryDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "6 Hilltop, Donegal",
                            RecipientName = "Ella Ferry",
                            Status = 2,
                            Type = 1,
                            Weight = 3.6000000000000001
                        },
                        new
                        {
                            Id = 35,
                            AttemptedDeliveries = 0,
                            Cost = 3.75,
                            CustomerId = 15,
                            DeliveryDate = new DateTime(2025, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "2 Oakfield, Clare",
                            RecipientName = "Ruby McBride",
                            Status = 0,
                            Type = 0,
                            Weight = 0.10000000000000001
                        });
                });

            modelBuilder.Entity("PackageDeliverySystem.Models.Models.Package", b =>
                {
                    b.HasOne("PackageDeliverySystem.Models.Models.Customer", "Customer")
                        .WithMany("Packages")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PackageDeliverySystem.Models.Models.Customer", b =>
                {
                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
