// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PackageDeliverySystem.DataAccess.DataAccess;

#nullable disable

namespace PackageDeliverySystem.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PackageDeliverySystem.Models.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 Hill St, Derry",
                            Name = "Emma OConnor"
                        },
                        new
                        {
                            Id = 2,
                            Address = "4 Main Rd, Letterkenny",
                            Name = "Sophie Gallagher"
                        },
                        new
                        {
                            Id = 3,
                            Address = "8 River Walk, Buncrana",
                            Name = "Aoife Kelly"
                        },
                        new
                        {
                            Id = 4,
                            Address = "22 Oak Ave, Dublin",
                            Name = "Sarah Murphy"
                        },
                        new
                        {
                            Id = 5,
                            Address = "9 Park Lane, Cork",
                            Name = "Lucy Boyle"
                        },
                        new
                        {
                            Id = 6,
                            Address = "1 Green Rd, Galway",
                            Name = "Grace Dunne"
                        },
                        new
                        {
                            Id = 7,
                            Address = "3 Harbour View, Sligo",
                            Name = "Mia Quinn"
                        },
                        new
                        {
                            Id = 8,
                            Address = "7 Meadow Rd, Limerick",
                            Name = "Hannah Ward"
                        },
                        new
                        {
                            Id = 9,
                            Address = "14 Bridge St, Waterford",
                            Name = "Chloe Reid"
                        },
                        new
                        {
                            Id = 10,
                            Address = "6 Hilltop, Donegal",
                            Name = "Ella Ferry"
                        },
                        new
                        {
                            Id = 11,
                            Address = "18 Pine Rd, Armagh",
                            Name = "Lily Kane"
                        },
                        new
                        {
                            Id = 12,
                            Address = "5 Cedar Ave, Newry",
                            Name = "Zoe Moore"
                        },
                        new
                        {
                            Id = 13,
                            Address = "11 Glen St, Dundalk",
                            Name = "Isla Byrne"
                        },
                        new
                        {
                            Id = 14,
                            Address = "20 Church Rd, Kilkenny",
                            Name = "Freya Sweeney"
                        },
                        new
                        {
                            Id = 15,
                            Address = "2 Oakfield, Clare",
                            Name = "Ruby McBride"
                        },
                        new
                        {
                            Id = 16,
                            Address = "17 Riverbank, Mayo",
                            Name = "Emily Gillen"
                        },
                        new
                        {
                            Id = 17,
                            Address = "9 Parkview, Wexford",
                            Name = "Anna Devlin"
                        },
                        new
                        {
                            Id = 18,
                            Address = "13 Main St, Monaghan",
                            Name = "Kate Curran"
                        },
                        new
                        {
                            Id = 19,
                            Address = "15 Hillcrest, Derry",
                            Name = "Olivia OBrien"
                        },
                        new
                        {
                            Id = 20,
                            Address = "19 Oak Rd, Strabane",
                            Name = "Ava McLaughlin"
                        },
                        new
                        {
                            Id = 21,
                            Address = "21 Harbour St, Galway",
                            Name = "Molly Gallagher"
                        },
                        new
                        {
                            Id = 22,
                            Address = "23 Station Rd, Cork",
                            Name = "Evie Kelly"
                        },
                        new
                        {
                            Id = 23,
                            Address = "25 Glen Rd, Dublin",
                            Name = "Niamh Murphy"
                        },
                        new
                        {
                            Id = 24,
                            Address = "27 Bridge Ave, Sligo",
                            Name = "Clara Boyle"
                        },
                        new
                        {
                            Id = 25,
                            Address = "29 Meadow View, Letterkenny",
                            Name = "Erin Doherty"
                        });
                });

            modelBuilder.Entity("PackageDeliverySystem.Models.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dept")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PPS")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PPS")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 Oak Drive, Derry",
                            DateOfBirth = new DateTime(1990, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dept = 0,
                            Name = "Sean Murphy",
                            PPS = "1234567AB",
                            Password = "pass123",
                            Salary = 35000.0,
                            Username = "driver1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Elm Park, Letterkenny",
                            DateOfBirth = new DateTime(1988, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dept = 0,
                            Name = "Conor Kelly",
                            PPS = "2345678BC",
                            Password = "pass123",
                            Salary = 36000.0,
                            Username = "driver2"
                        },
                        new
                        {
                            Id = 3,
                            Address = "22 Hillcrest, Dublin",
                            DateOfBirth = new DateTime(1992, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dept = 1,
                            Name = "Patrick Doherty",
                            PPS = "3456789CD",
                            Password = "admin123",
                            Salary = 50000.0,
                            Username = "admin1"
                        },
                        new
                        {
                            Id = 4,
                            Address = "7 Meadow View, Derry",
                            DateOfBirth = new DateTime(1999, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dept = 1,
                            Name = "Ethan Curran",
                            PPS = "4567890DE",
                            Password = "admin123",
                            Salary = 52000.0,
                            Username = "admin2"
                        });
                });

            modelBuilder.Entity("PackageDeliverySystem.Models.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 12.99,
                            CustomerId = 1,
                            Destination = "12 Hill St, Derry",
                            RecipientName = "Emma OConnor",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Cost = 4.9900000000000002,
                            CustomerId = 1,
                            Destination = "12 Hill St, Derry",
                            RecipientName = "Emma OConnor",
                            Status = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Cost = 18.989999999999998,
                            CustomerId = 2,
                            Destination = "4 Main Rd, Letterkenny",
                            RecipientName = "Sophie Gallagher",
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Cost = 4.5,
                            CustomerId = 2,
                            Destination = "4 Main Rd, Letterkenny",
                            RecipientName = "Sophie Gallagher",
                            Status = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Cost = 14.5,
                            CustomerId = 3,
                            Destination = "8 River Walk, Buncrana",
                            RecipientName = "Aoife Kelly",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Cost = 4.2000000000000002,
                            CustomerId = 3,
                            Destination = "8 River Walk, Buncrana",
                            RecipientName = "Aoife Kelly",
                            Status = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Cost = 22.5,
                            CustomerId = 4,
                            Destination = "22 Oak Ave, Dublin",
                            RecipientName = "Sarah Murphy",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Cost = 11.75,
                            CustomerId = 4,
                            Destination = "22 Oak Ave, Dublin",
                            RecipientName = "Sarah Murphy",
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Cost = 3.9900000000000002,
                            CustomerId = 5,
                            Destination = "9 Park Lane, Cork",
                            RecipientName = "Lucy Boyle",
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            Cost = 20.0,
                            CustomerId = 5,
                            Destination = "9 Park Lane, Cork",
                            RecipientName = "Lucy Boyle",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Cost = 10.75,
                            CustomerId = 6,
                            Destination = "1 Green Rd, Galway",
                            RecipientName = "Grace Dunne",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            Cost = 19.989999999999998,
                            CustomerId = 7,
                            Destination = "3 Harbour View, Sligo",
                            RecipientName = "Mia Quinn",
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            Cost = 11.5,
                            CustomerId = 8,
                            Destination = "7 Meadow Rd, Limerick",
                            RecipientName = "Hannah Ward",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            Cost = 24.989999999999998,
                            CustomerId = 9,
                            Destination = "14 Bridge St, Waterford",
                            RecipientName = "Chloe Reid",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            Cost = 12.75,
                            CustomerId = 10,
                            Destination = "6 Hilltop, Donegal",
                            RecipientName = "Ella Ferry",
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            Cost = 4.0999999999999996,
                            CustomerId = 10,
                            Destination = "6 Hilltop, Donegal",
                            RecipientName = "Ella Ferry",
                            Status = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 17,
                            Cost = 13.4,
                            CustomerId = 11,
                            Destination = "18 Pine Rd, Armagh",
                            RecipientName = "Lily Kane",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 18,
                            Cost = 21.0,
                            CustomerId = 12,
                            Destination = "5 Cedar Ave, Newry",
                            RecipientName = "Zoe Moore",
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 19,
                            Cost = 15.99,
                            CustomerId = 13,
                            Destination = "11 Glen St, Dundalk",
                            RecipientName = "Isla Byrne",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            Cost = 23.989999999999998,
                            CustomerId = 14,
                            Destination = "20 Church Rd, Kilkenny",
                            RecipientName = "Freya Sweeney",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            Cost = 8.9900000000000002,
                            CustomerId = 15,
                            Destination = "2 Oakfield, Clare",
                            RecipientName = "Ruby McBride",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 22,
                            Cost = 20.989999999999998,
                            CustomerId = 16,
                            Destination = "17 Riverbank, Mayo",
                            RecipientName = "Emily Gillen",
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            Cost = 3.5,
                            CustomerId = 17,
                            Destination = "9 Parkview, Wexford",
                            RecipientName = "Anna Devlin",
                            Status = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 24,
                            Cost = 12.49,
                            CustomerId = 18,
                            Destination = "13 Main St, Monaghan",
                            RecipientName = "Kate Curran",
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 25,
                            Cost = 19.489999999999998,
                            CustomerId = 19,
                            Destination = "15 Hillcrest, Derry",
                            RecipientName = "Olivia OBrien",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 26,
                            Cost = 13.99,
                            CustomerId = 20,
                            Destination = "19 Oak Rd, Strabane",
                            RecipientName = "Ava McLaughlin",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 27,
                            Cost = 22.989999999999998,
                            CustomerId = 21,
                            Destination = "21 Harbour St, Galway",
                            RecipientName = "Molly Gallagher",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 28,
                            Cost = 14.49,
                            CustomerId = 22,
                            Destination = "23 Station Rd, Cork",
                            RecipientName = "Evie Kelly",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 29,
                            Cost = 4.25,
                            CustomerId = 23,
                            Destination = "25 Glen Rd, Dublin",
                            RecipientName = "Niamh Murphy",
                            Status = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 30,
                            Cost = 21.989999999999998,
                            CustomerId = 24,
                            Destination = "27 Bridge Ave, Sligo",
                            RecipientName = "Clara Boyle",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 31,
                            Cost = 11.99,
                            CustomerId = 25,
                            Destination = "29 Meadow View, Letterkenny",
                            RecipientName = "Erin Doherty",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 32,
                            Cost = 9.9900000000000002,
                            CustomerId = 2,
                            Destination = "4 Main Rd, Letterkenny",
                            RecipientName = "Sophie Gallagher",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 33,
                            Cost = 9.9900000000000002,
                            CustomerId = 5,
                            Destination = "9 Park Lane, Cork",
                            RecipientName = "Lucy Boyle",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 34,
                            Cost = 19.5,
                            CustomerId = 10,
                            Destination = "6 Hilltop, Donegal",
                            RecipientName = "Ella Ferry",
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 35,
                            Cost = 3.75,
                            CustomerId = 15,
                            Destination = "2 Oakfield, Clare",
                            RecipientName = "Ruby McBride",
                            Status = 0,
                            Type = 0
                        });
                });

            modelBuilder.Entity("PackageDeliverySystem.Models.Models.Package", b =>
                {
                    b.HasOne("PackageDeliverySystem.Models.Models.Customer", "Customer")
                        .WithMany("Packages")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PackageDeliverySystem.Models.Models.Customer", b =>
                {
                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
